### ISSUE TITLE
Publish a `debug` version of the docker image per release

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#1296]
Related https://github.com/FuelLabs/fuel-core/pull/1286/files#r1290825419

**Comment by MitchTurner** [comment]
WRT manual block production (and other runtime flags), if we want to do it at runtime rather than at compile time, I think it would be best to have the consensus method fully encapsulated as an `enum` rather than having a bunch of flags.

I'd feel a lot better about exposing those flags in production in that case. Much easier understand the state of the system.

**Comment by xgreenx** [comment]
Clsoed by https://github.com/FuelLabs/fuel-core/pull/1322
