### ISSUE TITLE
Replace `fuel_core_client::client::types::ConsensusParameters` with `fuel_tx::ConsensusParameters`

### ISSUE THREAD

**Issue by sdankel** [FuelLabs/fuel-core#1312]
Currently there are three definitions of this type: 

- fuel_core_client::client::types::ConsensusParameters
- fuel_core_types::fuel_tx::ConsensusParameters
- schema::chain::ConsensusParameters

Some of the types are missing `from` and `default` impls, which makes it inconvenient to work with for unit testing in forc. 

There is a way to go from client -> fuel-tx [here](https://sourcegraph.com/github.com/FuelLabs/fuels-rs/-/blob/packages/fuels-core/src/types/wrappers/node_info.rs?L15:27)
And a way from schema -> client [here](https://sourcegraph.com/github.com/FuelLabs/fuel-core/-/blob/crates/client/src/client/types/node_info.rs?L14:40)
But missing fuel-tx -> client

Brandon K: 
> Hmm that type in fuel-core-client shouldn't be needed now, this should just be the fuel-tx version: https://github.com/FuelLabs/fuel-core/blob/master/crates/client/src/client/types/chain_info.rs#L14

We should be able to just replace `fuel_core_client::client::types::ConsensusParameters` with `fuel_core_types::fuel_tx::ConsensusParameters`

Similarly, for `NodeInfo`

**Comment by bvrooman** [comment]
I am able to remove the client type `ConesnsusParameters`, and directly swap in the `fuel_tx::ConsensusParameters` type in instances where it was used. 

However, I'm not finding an existing `fuel_tx` type for `NodeInfo`. Looking at the code again, it looks like this type is API level concept, existing only at the GraphQL layer and client abstraction layer. It is returned by an API call, rather than used internally by the client. That said, it doesn't I can give it the same treatment as `ConsensusParameters`. 

Maybe if can provide some more concrete context as to what you need to achieve,  I can look in that direction. Or if I'm just misunderstanding anything, please let me know!

**Comment by xgreenx** [comment]
Fixed by https://github.com/FuelLabs/fuel-core/pull/1314
