### ISSUE TITLE
Proposal to enhance the command line `fuel-core` commands

### ISSUE THREAD

**Issue by emilyaherbert** [FuelLabs/fuel-core#182]
I propose that we add the following commands:

1. `fuel-core start --options` as a replacement to `fuel-core --options`

2. `fuel-core stop` to stop the current instance
Implemented as a call to `ps aux | grep fuel-core`, parse the correct `PID`, then `kill <PID>` or alternatively we can use @nfurfaro  commands:
```bash
function kill4k
    kill -9 (lsof -t -i :4000)
end

function ignite
   alacritty --command fuel-core --ip 127.0.0.1 --port 4000 --db-type InMemory &
end

function reignite
  kill4k
  ignite
end
```

3. `fuel-core restart` to restart the current instance
Implemented as a call to `fuel-core stop` then `fuel-core start`

I think that this would enhance the pleasant interaction with `fuel-core` and would help developers iterate faster.

**Comment by Voxelot** [comment]
Rather than making fuel-core run in the background by default, what do you think about introducing something like the `--daemon` flag used in other apps like [emacs](https://www.emacswiki.org/emacs/EmacsAsDaemon)?

**Comment by Voxelot** [comment]
A daemon is a unix term for background process, so I'm suggesting that fuel-core would run in foreground as before by default and only spin up in the background when `--daemon` is used. However, it's a far less common practice to write servers as daemon processes in the current era of docker/kubernetes since it's harder to extract logs and track the status of the process. For example, if the server crashed or panicked (non-zero process exit code) you'd want the docker image to stop running so kubernetes could attempt to redeploy / auto-restart. Otherwise, you'd wind up with zombie servers not actually running a server process.

Coming at it from the Forc perspective, managing different installed versions of the cli vs the actual server isn't that uncommon. For example, if you `brew install docker` without also installing Docker Desktop you'll get an error from the docker cli saying there's no server to connect to. Forc could even prompt users to install fuel-core if it's missing.

**Comment by adlerjohn** [comment]
I'm generally hesitant to implement bash one-liners into the node itself. At most it could be in a wrapper (mono)binary. Seems very brittle and easy to shoot yourself in the foot.

Also, there's really no need for these commands. Users can just run the node in the foreground in another terminal tab with `--db-type in-memory`.

**Comment by adlerjohn** [comment]
W.r.t. to putting this in `forc`, `forc` is not meant to manage a node; it's meant to provide the necessary features to build, test, debug, and deploy contract, and nothing more. A plugin to `forc` can be built for additional functionality if needed, but the `forc` binary itself should not ship with node management functionality.

**Comment by xgreenx** [comment]
Closing as not needed
