### ISSUE TITLE
Transaction pool should take into account the amount of work caused by the transaction

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#1909]
## Overview
Instead of using raw tips, we need to use `tip / max_gas` to consider the amount of the work caused by the transaction. Super heavy transactions should have less priority than easier ones with the same `tip`.

## Implementation details
It would be nice to use fractions instead of floating numbers to sort transactions.

**Comment by AurelienFT** [comment]
@xgreenx I would like to tackle this issue. However I'm pretty new to contributing to this repository and so before coding can I ask if my idea of implementation seems ok to you ?

What I would do is that I would change the sorted `TipSort` by something like `TipPerGasSort` and each element instead of having a `tip: Word` field as it exists now, they would have a `tip_per_gas: Ratio<Word>` ([Ratio](https://docs.rs/num/latest/num/rational/struct.Ratio.html))

This would make a transaction that cause less work to ranked above others transaction that have a bit more tip but way more expected work. Is that a behavior that is ok to you ?

**Comment by xgreenx** [comment]
Yep, it is what should be done=) We plan to fix it this week, so you have two days before we start work on it=)

Also, don't forget to add a test!=)

**Comment by AurelienFT** [comment]
> Yep, it is what should be done=) We plan to fix it this week, so you have two days before we start work on it=)
> 
> Also, don't forget to add a test!=)

Here it is : https://github.com/FuelLabs/fuel-core/pull/1952 :)
