### ISSUE TITLE
Add support block size limit

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#2133]
Currently, the block is limited by the gas, and with the `63` gas per byte, the maximum size of the block can be `30000000/63 = 476_190` byte.

But since we want to have a hard limit 128kb or 256kb, we either need to increase the gas per byte, or add a new block size limit variable.

Support the block size limit requires:
- Add a new `block_size_limit` field to the consensus parameters.
- Updating the executor's logic to get transactions based on the remaining size.
- Update the transaction pool to support the limitation by size.

**Comment by xgreenx** [comment]
This feature requires breaking change into the WASM executor since we need to pass the size of the block when fetching transactions from the TxPool. It would be nice to release this breaking change along with https://github.com/FuelLabs/fuel-core/issues/2114 and https://github.com/FuelLabs/fuel-core/issues/1887

**Comment by rafal-ch** [comment]
A few comments w.r.t to implementation:
* new consensus parameter – `block_transaction_size_limit`
  * not `block_size_limit` due to what we’re gonna be actually limiting is the set of L2 transactions
* we’re ok if occasionally the block will get bigger than a limit due to L1 transactions, mint transaction or a header. Hence, if we want block to be limited to roughly 128kb, we coule set the `block_transaction_size_limit` to 125-126kb
* size of a transaction = size of the result of canonical serialization of transaction
