### ISSUE TITLE
Flaky test: `latest_binary_is_backward_compatible_and_follows_blocks_created_by_genesis_binary`

### ISSUE THREAD

**Issue by AurelienFT** [FuelLabs/fuel-core#2406]
Source https://github.com/FuelLabs/fuel-core/actions/runs/11571921587/job/32211080249?pr=2398
```
---- backward_compatibility::latest_binary_is_backward_compatible_and_follows_blocks_created_by_genesis_binary stdout ----
thread 'backward_compatibility::latest_binary_is_backward_compatible_and_follows_blocks_created_by_genesis_binary' panicked at forkless-upgrade/src/backward_compatibility.rs:118:14:
Timed out waiting for block import 8: Elapsed(())
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by rafal-ch** [comment]
There's been [an attempt](https://github.com/FuelLabs/fuel-core/pull/2301) to fix this, which helped, but seems like not to the full extent.

One additional idea was to run these tests one-by-one instead of in parallel by leveraging the `--test-threads=1` parameter, because maybe different instances of these tests can still interfere with each other.
