### ISSUE TITLE
Add total round count to fuel block header

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#399]
ref: https://github.com/FuelLabs/fuel-core/pull/380/files#r888454336

**Comment by adlerjohn** [comment]
Rounds sound not be part of the signed block header since round can change. Or rather, if round is included, then the block header hash that is signed over will change as the round increments, which might not be desirable. In Tendermint-Go, round is part of the Commit rather than the header, and is only signed over in the _next_ header.

**Comment by rakita** [comment]
In the new round, you have a new validator so it is most probable that the hash is going to be changed either way. The round definitely should be contained inside the Vote. But it shouldn't hurt to include it inside the header?

On the Tendermint topic, this is interesting thing to check out: https://pkg.go.dev/github.com/tendermint/tendermint/types#Block

**Comment by xgreenx** [comment]
@Voxelot, I guess we can close this issue for now?
