### ISSUE TITLE
Potential issue with maturity during contract deployment.

### ISSUE THREAD

**Issue by segfault-magnet** [FuelLabs/fuel-core#449]
The minimal example can be found [here](https://github.com/segfault-magnet/tx-maturity-minimal-example).
It has two tests:

1. Calling a contract will only succeed if the transaction maturity is <= the current block height.
2. Deploying a contract will only succeed if the transaction maturity is <= the current block height.

The second one fails with `PredicateFailure`.

`Cargo.toml` has been set-up to use `fuel-vm` with revision `6d6fe76f45bfd33348930e04cd75ac9741b46d11` which points to 
```
Author: Brandon Kite <brandonkite92@gmail.com>
Date:   Mon Jun 27 13:17:36 2022 -0700

    fix block height when performing tx validation (#154)

    * fix block height when performing tx validation
```
which fixes the first test in the minimal example.

`Cargo.toml` also points to a version of the SDK under development which actually forwards the maturity through the gql client. The SDK uses the latest release of `fuel-core` '^0.9'

AFAICS this can happen for one of three reasons:

1. there is something about maturity and contract deployment that I don't understand, and this should fail the way it does
2. something changed in `fuel-vm` between the version that `fuel-core` master uses and the revision used in `Cargo.toml` which causes this issue since `fuel-core` wasn't adapted yet.
3. There is actually a bug with handling `maturity` for `Create` transactions.

**Comment by Voxelot** [comment]
It appears this is due to a couple of issues:

1. The VM is attempting to perform predicate verification for any creation transactions regardless of whether there are any predicates, however the VM should leave the responsibility of executing predicates to the client.
2. Predicate verification is supposed to be stateless, however since the VM is performing transaction validation on initialization it just sets the block height to 0 for predicates.

The immediate fix will be to simply disable automatic predicate verification for creation transactions in the VM, which will partially unblock the issue as create txs without predicates will start working. 

To fix the block height/maturity issue for predicate verification, the ideal solution is to switch the VM to only accept [`CheckedTransaction`](https://github.com/FuelLabs/fuel-tx/pull/155)'s. This will remove the need for the VM to perform any transaction validation at all, and let the client properly validate transactions before passing them to the VM.

cc @vlopes11

**Comment by Voxelot** [comment]
closed by https://github.com/FuelLabs/fuel-vm/pull/173
