### ISSUE TITLE
Decompose DummyDb from fuel-core-interfaces into module specific dummy databases

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#517]
Right now we are overloading a global database test fixture that implements all the traits from all the different modules in the client. Each module already defines a database interface for the areas it's concerned about, and shouldn't require additional test data from other modules. Test data should be isolated to the module it is used in. Global reuse of test data may lead to unforeseen and difficult to solve side effects and unexpected behavior in unit tests.

For example, the txpool uses globally defined dummy transactions (TX_1, TX_2, etc) to fill the dummy db. This creates a lot of noise, which isn't scalable as more modules add test data, and generally increases the complexity of writing tests.

Eliminate DummyDb from fuel-core-interfaces, and migrate all related test data & setup to each respective crate module.

**Comment by bvrooman** [comment]
Related:  https://github.com/FuelLabs/fuel-core/issues/561

**Comment by bvrooman** [comment]
I am considering moving the txpool tests and `MockDb` to a separate `tests` folder under `fuel-txpool`. I think this would make code cleaner and more maintainable. In order to have proper reuse of `MockDb` in other areas of `fuel-txpool`, this may mean moving other unit test suites into `tests` as well, causing a cascade of changes. In the meantime, I've left `mock_db.rs` under `src` under a test cfg flag.
