### ISSUE TITLE
Include messages in coinsToSpend API

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#586]
When a user wants to transfer some funds or pay for gas, they need to call the coinsToSpend API to obtain a set of spendable inputs to use. With the addition of messages as a new type of spendable input, the coinsToSpend API should be expanded to also include messages received from L1 in addition to coins.

The current coinsToSpend API uses the random-improve algorithm to minimize utxo dust. While spending messages can't remove dust, there may be cases where using a message instead of a coin can help prevent the creation of dust. Until we have better modeling for this, messages should just be treated interchangeably for coins as an extension of the coin set for both random & largest first based selection.

**Comment by xgreenx** [comment]
Right now, the signature of the `coinsToSpent`:

```rust
struct SpendQueryElementInput {
    /// Asset ID of the coins
    asset_id: AssetId,
    /// Target amount for the query
    amount: U64,
}

type Asset = SpendQueryElementInput;

fn coinsToSpent(
    // Owner of the coins.
    owner: Address, 
    // The list of requested assets` coins with asset ids and the target
    // amount the user wants to reach. We allow several entries with
    // the same asset id.
    assets: Vec<Asset>, 
    // The maximum number of coins that we can return. 
    // It doesn't take into account that for some asset id `X`, 
    // we want to use `N` inputs, and for some asset id `Y`, 
    // we want to use `M` inputs.
    max_coins: Option<u64>,
    // The list of excluded `UtxoId`s during iterating over the coins.
    exclude: Option<Vec<UtxoId>>,
)
// The list of `Coin`s for **all* assets combined together and
// limited by `max_coins`.
-> Result<Vec<Coin>>
```

It is a simplified model for better understanding.

## Return type proposal

With the introduction of `Message`, the query should accept filtering by `MessageId`, and return both `Coin`s and `Message`s.

For return type, we can use `enum`. But how do we want to name the entity that holds `Coin`s and `Message`s? In the PR, I named it `Banknote` as the analog of paper banknotes in real life. But as Brandom notices "Hmm I wouldn't call it banknotes, as there's no bank and they aren't notes".

We can't use `Asset` because it is name for fungible tokens in the network. We can't use `Input` or `Output` because it is reserved for transactions.

Maybe someone has ideas on how better to name it=) As an alternative to `Banknote`, I propose `Currency`.

## Exclude Utxos proposal

Due to the [limitation](https://github.com/async-graphql/async-graphql/issues/373) of the `async-graphql` we can't have complex enums as inputs. So we can't make `exclude: Option<Vec<CurrencyId>>` where:

```rust
enum CurrencyId {
    Utxo(UtxoId),
    Message(MessageId),
}
```

The possible solution is to create a separate `Exclude` struct with a different `Vec` inside.

```rust
pub struct ExcludeInput {
    /// Utxos to exclude from the selection.
    utxos: Vec<UtxoId>,
    /// Messages to exclude from the selection.
    messages: Vec<MessageId>,
}
```

## Input and output per asset proposal

It is strange that the query accepts the list of different assets but returns one vector for all those assets. I propose to change the return type from the `Vec<Currency>` to `Vec<Vec<Currency>>`. For each asset, we will return its vector with currencies. Together with it, I propose to move `max_coins` into `SpendQueryElementInput` because it is more logical. As the final step, I propose not to allow(return an error to the caller) duplicate `asset_id` in the `assets`, to avoid merging and facing conflicts with `max_coins_per_asset`.

## Renaming of the method

Because we return not `Coin`s anymore, we also should change the name. If we will chose `Currency`, the name `currenciesToSpent`.

## The final signature

With all proposals the final method signature:

```rust
struct SpendQueryElementInput {
    /// Asset ID of the coins
    asset_id: AssetId,
    /// Target amount for the query
    amount: U64,
    /// The maximum number of currencies for selection.
    max: Option<U64>,
}

type Asset = SpendQueryElementInput;

pub struct ExcludeInput {
    /// Utxos to exclude from the selection.
    utxos: Vec<UtxoId>,
    /// Messages to exclude from the selection.
    messages: Vec<MessageId>,
}

pub enum Currency {
    Coin(Coin),
    Message(Message),
}

fn currenciesToSpent(
    // Owner of the coins.
    owner: Address, 
    // The list of requested assets` currencies with asset ids, `target`
    // amount the user wants to reach, and the `max` number of currencies 
    // in the seleciton. Several entries with the same asset id are not allowed.
    assets: Vec<Asset>, 
    // The excluded currencies from the selection.
    exclude: Option<ExcludeInput>,
)
// The list of `Currency`s per each asset. The length of the result is 
// the same as the length of the `assets`.
// The ordering of currencies per asset is the same.
-> Result<Vec<Vec<Currency>>>
```

**Comment by xgreenx** [comment]
It doesn't affect it anyhow=) The `owner` is the field of the `Message`, but the proposal doesn't touch the `Message` itself.

The proposal has part related to the integration of `Message`s into the query and part related to clarification of the query itself(the previous signature of the query is ambiguous).

**Comment by nfurfaro** [comment]
>how do we want to name the entity that holds Coins and Messages?

Maybe `Spendable` ?
```
enum Spendable { 
    Coin: ...,
    Message: ...,
}
```

**Comment by xgreenx** [comment]
In the future, we will have a query that returns the list of all coins and messages (Spent and NotSpent). So, we need some naming for spendable and not spendable coins and messages.

**Comment by nfurfaro** [comment]
So we need to convey the idea that the thing has a property of being `Spendable`, while also having a state of either `Spent` or `Unspent`

**Comment by pixelcircuits** [comment]
> Messages no longer have an `owner` field as of [FuelLabs/fuel-specs#400](https://github.com/FuelLabs/fuel-specs/pull/400). They only have a `recipient`. Does that affect this proposal?

The `owner` field is really just being reused as `recipient`, and the old `recipient` is going away. I don't see anything wrong with still calling it `owner` is the global `currenciesToSpent`. It'll just be implied it means `owner` or `recipient`

**Comment by pixelcircuits** [comment]
I tend to like the `Spendable` nomenclature

**Comment by pixelcircuits** [comment]
Why make a whole new `ExcludeInput ` struct and not just have two exclude lists in `currenciesToSpend`?

**Comment by Voxelot** [comment]
The proposed usage of the word asset seems off to me. I'd think of any particular coin or message as a user's asset. 

Aliasing a spendQuery as an asset doesn't seem right:

1. An asset doesn't refer to a grouping of valuable objects, it is a singular spendable object.
2. A query for a set of assets != an asset itself.

Also, the API should be _toSpen**d**, as the tense of _toSpen**t** implies the coins were already spent.

Here's my proposal:

```rust
struct SpendQueryElementInput {
    /// Asset ID to spend
    asset_id: AssetId,
    /// Target amount for the query
    amount: U64,
    /// The maximum number of currencies for selection.
    max: Option<U64>,
}

pub struct ExcludeInput {
    /// Utxos to exclude from the selection.
    utxos: Vec<UtxoId>,
    /// Messages to exclude from the selection.
    messages: Vec<MessageId>,
}

pub enum Asset {
    Coin(Coin),
    Message(Message),
}

fn assetsToSpend(
    // Owner of the coins.
    owner: Address, 
    // The list of requested assets` currencies with asset ids, `target`
    // amount the user wants to reach, and the `max` number of currencies 
    // in the seleciton. Several entries with the same asset id are not allowed.
    spendQuery: Vec<SpendQueryElementInput>, 
    // The excluded currencies from the selection.
    exclude: Option<ExcludeInput>,
)
// The list of spendable assets per query. The length of the result is 
// the same as the length of `spendQuery`.
// The ordering of assets and spendQuery is the same.
-> Result<Vec<Vec<Asset>>>
```

**Comment by xgreenx** [comment]
> Why make a whole new ExcludeInput struct and not just have two exclude lists in currenciesToSpend?

Because it is more extendable in the future(if we add new types of \*reserved name for spendable and non-spendable entity what we try to find\*). And it doesn't bloat the method signature=)

> In addition aliasing type Asset = SpendQueryElementInput; doesn't seem right:

I added this alias for simplification because, on my screen, the line was too long=) It is why I didn't rename `SpendQueryElementInput` itself. The correct argument name is `query_per_asset`. 

Based on your comment, it seems you agree with "Exclude Utxos", "Input and output per asset", and "Return type" proposals. The last one that we need to decide on is naming=)

> Also, the API should be _toSpend, as the tense of _toSpent implies the coins were already spent.

You are correct, I meant "...ToSpen**d**", typo.

> I'd think of any particular coin or message as an asset of the user.

I like the naming "asset" for coins and messages. The problem is that this name is already reserved for fungible tokens. We have `AssetId`(previously `ColorId`), and, logically, it belongs to the `Asset`.

If coins and messages are assets, we have the subsequent confusion:
The id of the `Coin` is `UtxoId`, but it is `Asset` at the same time, and the `Coin` contains `AssetId` inside, the developer can think that this `AssetId` is an id of the `Coin`, but it is wrong.

Another example, I'm sure in the future, we will have this kind of API:

```rust
// Return the list of asset ids(fungible tokens) used by the network.
fn asset_ids() -> Vec<AssetId>;

// Return the list of spendable assets ids owned by the `owner` of some `asset_id`.
fn assets_ids_to_spend(owner: Address, asset_id: AssetId) -> Vec<???>; 
//                                                               ^^^
// Here we need to return an `enum` with `UtxoId` and `MessageId`. 
// We called coins and messages - `Asset`, so the logic is that we need to call 
// the enum(their ids) - `AssetId`. But this name is already reserved=)

// The list of spendable assets per query. The length of the result is 
// the same as the length of `spendQuery`.
// The ordering of assets and spendQuery is the same.
fn assets_to_spend(...) -> Vec<Vec<Asset>>;
```

And here we have a problem with how to name `???` and description of methods works with "assets", but it is different assets.

**Comment by Voxelot** [comment]
> the developer can think that this AssetId is an id of the Coin, but it is wrong.

This is an unfortunate potential oversight that already exists today, but I do see how proliferating the usage of the word asset into different contexts could worsen potential confusion 🤔 

Rather than trying to future proof the return type, another approach to avoid all this ambiguity is to just be super specific with the semantics of this API.

e.g. 

```rust
fn select_inputs_to_spend(...) -> Vec<Vec<SpendableInput>>
```

Since we already have another API for querying ownedMessages, I don't think we need to worry too much about a unified `getAllOwnedCoinsAndMessages` API in the near future.

**Comment by xgreenx** [comment]
This will be our choice if we cannot find one word to describe spendable and non-spendable coins and messages=)

But I prefer to use `Spendable` without `Input`. Because `Input`s are spendable by default, and I don't want to overload it more=) We already have other places with `Input`.

BTW, What do you think about "resource"? It is a very neutral word and describes the user's resources(consumed and not consumed).

**Comment by Voxelot** [comment]
I doubt we'd need to use the word `resource` for anything else 🤔 It also seems slightly better than something really generic like `Object`. :shipit:
