### ISSUE TITLE
use semaphore or restricted size threadpool for dry_run block execution

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#752]
By default, the block executor runs directly on the calling thread. While this may be appropriate to ensure lively block production, dry_run calls triggered by API users should be rate limited and processed on blocking threads to prevent the tokio runtime from stalling or becoming unresponsive.

As a start, we could configure tokio with a limited size blocking threadpool with long keep-alive (to reduce overhead). Each dry_run request should use this size restricted threadpool to offload work from the tokio runtime and limit the number of concurrent execution requests. This will allow other APIs to remain responsive and also prevent block production from being stalled by the API.

cc @freesig

**Comment by freesig** [comment]
You probably don't want a long keep alive that is too long because if there is nothing happening you want to close the threads. You want enough so that the threads stay open between constant dry run calls. A semaphore would be useful if we want to limit the dry runs more then the available worker threads (because we want to keep a few for other uses) but if this is not the case we can just let tokio limit the worker threads. `spawn_blocking` will yield if there are no available worker threads.

I also think we should do some basic perf with a few workloads and generate some flamegraphs / look at what is being saturated (IO or cpu or network etc) so we have some idea of what we might be facing. 
@Voxelot did make a good point though that it could really be transaction dependent as a script / contract could make lots of db calls vs another that has no db calls and is all signing / hashing.
