### ISSUE TITLE
Allow for GraphQL batch requests in fuel-client

### ISSUE THREAD

**Issue by deekerno** [FuelLabs/fuel-core#764]
After discussing how to best implement optimized transaction fetching for https://github.com/FuelLabs/fuel-indexer/issues/288, @ControlCplusControlV suggested that an issue be created for allowing for batch requests in the `fuel-client` endpoints. This would allow for multiple requested units of information to be returned in a single request rather than a new request per unit of desired info.

More information: https://docs.rs/async-graphql/latest/async_graphql/enum.BatchRequest.html

**Comment by ra0x3** [comment]
@ControlCplusControlV Checking in on this
- @deekerno apparently took a stab at this and determined he'd need some help with this
- Since we already have a `client.transaction(id: TransactionIdFragment) -> Transaction` API and we're just trying to get a `client.transactions(ids: Vec<TransactionIdFragment>) -> Vec<Transactions>` (ideally) I feel like this new functionality would be a pretty quick task? Maybe we could pair on this?
- Ideally we'd like to have this done in time for the PoA Mainnet milestone (11/30) unless there's something bigger under the surface that I'm missing here that would prevent us from being able to easily implement this 🤔

**Comment by Voxelot** [comment]
Should we postpone this issue / push it onto the indexer block explorer module? Given that we are looking to deprecate / remove the usage of graphql in fuel-core moving forward.

**Comment by ControlCplusControlV** [comment]
Yes, this has to be moved into the indexer side since `fuel-core`'s api architecture will likely change to something non GQL, and so it will be on the indexer to implement GQL batching

**Comment by ra0x3** [comment]
@Voxelot 
- Do we have a set timeline for that? There are people actually using the indexer for beta2  (one individual using it that comes to mind seems to be using the indexer pretty seriously and helping us find bugs along the way). 
- If we plan to make substantial progress on this in the not-too-distant future I think this can wait
- However, if we're talking about 30+ days until we revisit this I think maybe we should go ahead and solve for it now

**Comment by Voxelot** [comment]
Looked into the issue again and noticed a couple things:

1. beta2 already supports batch graphql queries as async-graphql automatically gives this to us for free. The limitation is on the fuel-gql-client side which uses the library cynic. Since it doesn't provide any macros or examples for doing this out of the box, and the query DSL is undocumented, it would take a bit of effort to finagle batch requests into it.
2. An alternative to batch requests, is to utilize the GraphQL block api better for this use-case from the fuel-gql-client as the API already provides a full list of the transactions for each block in the block query schema. We could make a new block API on the fuel-gql-client that returns the full block + all transactions ( + status).

**Comment by ControlCplusControlV** [comment]
> An alternative to batch requests, is to utilize the GraphQL block api better for this use-case from the fuel-gql-client as the API already provides a full list of the transactions for each block in the block query schema. We could make a new block API on the fuel-gql-client that returns the full block + all transactions ( + status).
 
 I think this makes the most sense, since we are refactoring the GQL endpoint into indexer anyway and will probably move to something like JSON-RPC which will have a different batching process anyway

**Comment by ra0x3** [comment]
@Voxelot like @ControlCplusControlV I like that second option and think maybe we should do that if it sounds feasible/reasonable (given everything else you guys have to do)? 👌

**Comment by xgreenx** [comment]
@ra0x3 I am closing this issue because GraphQL already provides a way to fetch everything in one request=) If you need any other batch request, you can use the idea from https://github.com/FuelLabs/fuel-indexer/issues/288 to do that=)
