### ISSUE TITLE
Trying to deploy to beta-2 testnet with https returns an invalid url scheme

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/fuel-core#793]
I am not sure if this is related to the deployment configuration or related to here but trying to deploy a contract to the beta-2 test net with `forc deploy --url https://node-beta-2.fuel.network/graphql --gas-price 1` returns graphql error: invalid URL, scheme is not http. Switching https://node-beta-2.fuel.network/graphql to http://node-beta-2.fuel.network/graphql fixes this.

**Comment by ControlCplusControlV** [comment]
```
Error: Custom { kind: Other, error: "Graphql error: HttpStream(hyper::Error(Connect, \"invalid URL, scheme is not http\"))" }
```

Full error message, seems [hyper_tls](https://docs.rs/hyper-tls/latest/hyper_tls/) may be needed somewhere

**Comment by ControlCplusControlV** [comment]
So I've traced the dep. We use `cynic` in `fuel-client` which in the deployed (but not current build) uses `surf` which then has an upstream dep on `hyper` because [cynic doesn't use rust-ls](https://github.com/obmarg/cynic/blob/master/cynic/Cargo.toml#L19) I think? Continuing to debug but posting update here
