### ISSUE TITLE
Define and implement the strategy for the block timestamps after failing to produce in time

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#918]
The current logic of `PoA` uses the `Tai64::now` during block production without worrying about the block production delays (it also could be a crash or restart of the node).

With a multi-node environment, each peer should verify the block, and the timestamp is one of the things to verify.

In the `PoA` consensus with the solo producer, it is a normal strategy only to require the next timestamp to be `>=` of the previous one. But we have different block production strategies, `Interval` or `Hybrid`, that have the average `block_time` and the `max_block_time`(it means `next_block_height <= prev_block_time + max_block_time`).

This issue is a place to discuss what is expected behavior and requires corresponding PR to fix the problem(on the `PoA` side and checker side). Maybe we can forbid/remove `Hybrid` mode and have simple rules for `Interval`.

Also, it requires proper handling of the previous block timestamp on the `PoA` service side because it currently ignores time spent on the block production.

I disabled the timestamp check for now while this issue is not resolved.

**Comment by Voxelot** [comment]
I don't think we want to remove hybrid, as it gives us the ability to responsively produce blocks without spamming the blockchain during periods of inactivity.

Simply checking that the next timestamp >= the previous should be sufficient for any PoA mode, since we are already bound to trusting the single producer anyways otherwise you'll have to stop following the chain entirely. It becomes more of an issue in situations where we have multiple producers and need to validate things like slots per epoch etc.

**Comment by xgreenx** [comment]
We had an internal discussion and decided to follow the simple rule for any PoA version where the next block should be higher than the previous one.

We removed the block production strategy from the `ChainConfig`, and now it is configured individually via the argument of the `fuel-core`.

**Comment by xgreenx** [comment]
Created a separate task to patch timer https://github.com/FuelLabs/fuel-core/issues/966
